### ISSUE TITLE
UGS Nightly Platform ( DOOR STATE problem).

### ISSUE THREAD

**Issue by mtim80** [winder/Universal-G-Code-Sender#1292] opened 2019-10-24 12:35 UTC
Hi!

Problem with Door state. When jogging and door state triggered, buffer will clear, but while in that state I can push jog actions to buffer and they will be executed after resume.  Shouldn't those jogging commands be unactivated while DOOR STATE?  You can accidentally push joystick stick or buttons, and make unwanted actions after resume. Is there something I can do to avoid this behaviour?

Nightly platform 2.0 
Grbl 1.1 
Win10 

- thanks in advance!

**Comment by breiler** [comment] 2023-02-23 19:30
Closing as I can't reproduce the error anymore.

**Closed by breiler** 2023-02-23 19:30 UTC
