### ISSUE TITLE
Send button not available

### ISSUE THREAD

**Issue by AndyColorado** [winder/Universal-G-Code-Sender#2184] opened 2023-03-28 16:42 UTC
### Version

2.0.14

### Hardware / Firmware

GRBL 1.1

### What happened

Finished getting everything ready to start.  "Send" button is greyed out.  Saw another post that said on the first time loading, you have to use the start under "Machine".  Button is greyed out there, too.  Saw another post that said it was fixed 4 years ago.  Obviously, I'm still having this problem.

### How to reproduce

Pretty simple.  Went through all steps for putting together a file.  Send button not available.  Started over and created a completely new file.  Same problem.  Double checked all entries both times.

### Operating System

Windows 10

### Anything else

Every time, although, this is the first file trying to run through UGS.

**Comment by breiler** [comment] 2023-04-05 13:54
Closing as we didn't get a response from user and not able to reproduce the problem.

**Closed by breiler** 2023-04-05 13:54 UTC
