### ISSUE TITLE
EXCEPTION_ACCESS_VIOLATION (0xc0000005) when opening serial port

### ISSUE THREAD

**Issue by dgtlmoon** [winder/Universal-G-Code-Sender#386] opened 2016-04-08 15:39 UTC
Hi,

As soon as I open the serial port with the application, it crashes.

This is with the current nightly build (classic GUI) the issue also exists with the UGS build.

I'm running Java/jre 9 because 8 does not support HiDPI displays and unfortunately most 4K LCD laptops (like this XPS 15) cant really be 'tuned down' because the display looks horrible.

Java 9 adds support for scaling of the text (otherwise the text looks 4 times smaller than usual)

[log.txt](https://github.com/winder/Universal-G-Code-Sender/files/210410/log.txt)

```C:\Users\dgtlmoon\Desktop\gcodesender>"c:\Program Files\Java\jre-9\bin\java" -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+113)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+113, mixed mode)```

Log attached, I'm running windows 10.

I have no problems using the chilipepper serial port server

**Comment by winder** [comment] 2016-04-08 15:56
Duplicate of #369 

I created an issue with JSSC: https://github.com/scream3r/java-simple-serial-connector/issues/90

**Closed by winder** 2016-04-08 15:56 UTC
Labels: duplicate
