### ISSUE TITLE
Faulty Return to 0

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#372] opened 2016-03-22 15:07 UTC
Sometimes when I decide to use return to 0, it will raise the Z by about 600mm or so.....not ideal. I end up just command lining the jogs to get back to my work 0 instead of the button. 

Will, Plz fix

**Comment by winder** [comment] 2016-03-22 15:49
Duplicate of #308

**Closed by winder** 2016-03-22 15:49 UTC
Labels: bug, duplicate
