### ISSUE TITLE
Dialog Boxes not showing up

### ISSUE THREAD

**Issue by N0TB0T** [winder/Universal-G-Code-Sender#2449] opened 2024-02-02 13:30 UTC
### Version

2.1.4

### Hardware / Firmware

GRBL 1.1

### What happened

The dialog boxes for no matter what ("Open File", "Options", ...) won't open. Only immediately after a restart, there's a guarantee they will, but after some clicks here and there, menu items will turn blue/selected when clicked, but nothing happens. Can't run two files after another.

### How to reproduce

Can reproduce behaviour any time when running UGS.

### Operating System

Windows 10, nothing special at all.

**Comment by breiler** [comment] 2024-02-02 13:41
Please attach your log file from 
C:/Users/[your username>]/AppData/Roaming/ugsplatform/var/log/messages.log

**Comment by N0TB0T** [comment] 2024-02-02 17:41
So I guess it comes down to:

"java.lang.InternalError: The current process has used all of its system allowance of handles for Window Manager objects"

?

**Comment by breiler** [comment] 2024-02-07 19:41
Sorry for the late reply. 

I have no idea what is causing this error. Similar message has occurred for this user:
https://github.com/winder/Universal-G-Code-Sender/issues/2417

I am wondering if dropbox is doing strange things with the files? Maybe try placing UGS in another directory, `C:\Users\buddybrand` for instance?

**Comment by N0TB0T** [comment] 2024-02-07 19:46
There might be some flagging/locking going on in the background, i don't know either. Since moving the files to another location (C:) everything's smooth.Am 07.02.2024 20:41 schrieb Joacim Breiler ***@***.***>:
Sorry for the late reply.
I have no idea what is causing this error. Similar message has occurred for this user:
#2417
I am wondering if dropbox is doing strange things with the files? Maybe try placing UGS in another directory, C:\Users\buddybrand for instance?

**Comment by breiler** [comment] 2024-03-14 14:52
This was likely caused by this issue #2465, fixed in UGS v2.1.6

**Closed by breiler** 2024-03-14 14:52 UTC
