### ISSUE TITLE
Macros pane does not function

### ISSUE THREAD

**Issue by cjbaar** [winder/Universal-G-Code-Sender#668] opened 2017-06-10 01:46 UTC
I apologize in advance for re-posting this, but I couldn't figure out how to re-open an older post, and this issue does not appear to have changed. I am using UGS platform. I am downloading using the link shown here, under the "Nightly Builds" section, as it seems to be the most relevant I can find. I am unable to find any version information in the application (other than the version of Java/NetBeans) so I don't know how to tell if it is current or not.
<img width="879" alt="screen shot 2017-05-14 at 11 53 46 am" src="https://user-images.githubusercontent.com/1058385/26998969-6d9c7cf2-4d4b-11e7-8df5-79e7f46998e2.png">

This problem has persisted since I started using UGS. I am creating macros using the preferences window.
<img width="701" alt="1" src="https://user-images.githubusercontent.com/1058385/26998970-81e44546-4d4b-11e7-91a1-c9b2e427d3a2.png">

This creates a button in the Macros pane.
<img width="357" alt="2" src="https://user-images.githubusercontent.com/1058385/26998972-8d3cbd4c-4d4b-11e7-9560-8603fc139177.png">

However, clicking on this button does nothing. No commands are sent, as shown in the console output here.
<img width="429" alt="3" src="https://user-images.githubusercontent.com/1058385/26998976-9a6fe39a-4d4b-11e7-8e86-36f112117177.png">

I would appreciate any advice on what I may be missing. I have gone through this several times, and re-download UGS each time but no changes appear to have been made. Thank you.

**Comment by poisa** [comment] 2017-06-15 21:11
Just came here to report the same.

**Comment by winder** [comment] 2017-06-20 09:51
@cjbaar @poisa first of all, sorry for the delay. I reviewed your comments in #636 and haven't been able to reproduce the issue yet.

What version of GRBL are you connecting to?
What OS are you using?
If you launch UGS from the command line are any errors reported?
When you click the macro button do you see a red symbol in the bottom right corner of the platform GUI? If yes please click it and copy the error message here.

One thing you can try is to delete the cache directory, you can find its location on the `About` page:
http://winder.github.io/ugs_website/img/platform/about_popup.png

**Comment by winder** [comment] 2017-06-20 09:52
Some other questions occurred to me:

do the macro button in the settings panel work?
do the macro menu items work?

**Comment by vMeph** [comment] 2017-06-20 10:55
try delete the temps data hide?
\AppData\Roaming.ugsplatform

**Comment by poisa** [comment] 2017-06-20 14:45
> What version of GRBL are you connecting to?

1.1

> What OS are you using?

macOS Sierra 10.12.5 (16F73)

> If you launch UGS from the command line are any errors reported?

No. Just this:
```
Loading LocalizingService...
Initializing...
Loading JogService...
Loading ActionService...
Loading MacroService...
Loading StatusLineService...
Services loaded!
Initializing firmware... ...
/resources/firmware_config/
/resources/firmware_config/tinyg.json
/resources/firmware_config/smoothieboard.json
/resources/firmware_config/test_1.json
/resources/firmware_config/grbl.json
/resources/firmware_config/test_2.json
Setting changed
Is enabled: false
```

> When you click the macro button do you see a red symbol in the bottom right corner of the platform GUI? If yes please click it and copy the error message here.

No.

> One thing you can try is to delete the cache directory, you can find its location on the About page:
http://winder.github.io/ugs_website/img/platform/about_popup.png

I don't have that dir. I mean, I have all the tree except for the cache part. Could this probably be because I just re-installed the nightly build and haven't connected it to the CNC yet?

> Do the macro button in the settings panel work?

Didn't try this. I will as soon as I'm near the CNC this afternoon.

> Do the macro menu items work?

They change their label and are enabled but nothing seems to happen when I click them (the logs don't show anything and there are no error messages anywhere).

**Comment by poisa** [comment] 2017-06-21 00:01
>Do the macro button in the settings panel work?

Just tried this and they don't work either.

I re-tried the same steps with an older version of UGS and the latest nightly build both with same results.

The GRBL version is actually `1.1f` (not `1.1` as I stated before).

**Comment by poisa** [comment] 2017-06-21 00:16
I installed the latest version on a different machine which never had UGS before and finally got something that might be useful to debug this. After touching one of the macro buttons on the main panel (not the preferences panel) I got a red "minus" sign at the bottom with the following:

java.lang.NoSuchMethodError: com.willwinder.universalgcodesender.model.Position.getX()D
	at com.willwinder.universalgcodesender.model.GUIBackend.updateSystemState(GUIBackend.java:365)
	at com.willwinder.universalgcodesender.MacroHelper.substituteValues(MacroHelper.java:86)
	at com.willwinder.universalgcodesender.MacroHelper.executeCustomGcode(MacroHelper.java:46)
	at com.willwinder.universalgcodesender.uielements.macros.MacroActionPanel.customGcodeButtonActionPerformed(MacroActionPanel.java:170)
	at com.willwinder.universalgcodesender.uielements.macros.MacroActionPanel.lambda$doLayout$0(MacroActionPanel.java:100)
	at com.willwinder.universalgcodesender.uielements.macros.MacroActionPanel$$Lambda$63/943909185.actionPerformed(Unknown Source)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6525)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjbaar** [comment] 2017-06-24 02:55
My grbl is 0.9j, desktop is OS X 10.10.5. When I click on the macro, I see the red icon, and it provides the following. At first glance, it appears the same as @poisa 

java.lang.NoSuchMethodError: com.willwinder.universalgcodesender.model.Position.getX()D
	at com.willwinder.universalgcodesender.model.GUIBackend.updateSystemState(GUIBackend.java:366)
	at com.willwinder.universalgcodesender.MacroHelper.substituteValues(MacroHelper.java:86)
	at com.willwinder.universalgcodesender.MacroHelper.executeCustomGcode(MacroHelper.java:46)
	at com.willwinder.universalgcodesender.uielements.macros.MacroActionPanel.customGcodeButtonActionPerformed(MacroActionPanel.java:170)
	at com.willwinder.universalgcodesender.uielements.macros.MacroActionPanel.lambda$doLayout$0(MacroActionPanel.java:100)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6535)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6300)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4891)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4713)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
[catch] at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cjbaar** [comment] 2017-06-24 02:57
I have deleted the cache directory, but no change. The macros button in the settings panel does not work, and I have no items showing the macros menu.

**Comment by vMeph** [comment] 2017-06-24 11:39
did you delete the temp files hiden ??
 C:\AppData\Roaming\.ugsplatform

**Comment by poisa** [comment] 2017-06-24 16:18
I'm not no Windows, so no.

>

**Comment by sdarocha** [comment] 2017-10-20 18:15
@cjbaar and @poisa did you solved the problem? Same problem with me. Thank you.

**Comment by poisa** [comment] 2017-10-20 18:29
No, I just learned to live with it. I don’t do this professionally so it’s
ok.

**Comment by winder** [comment] 2017-10-20 18:45
I missed the stacktrace from @cjbaar back in June, I just added a fix for it.

**Comment by sdarocha** [comment] 2017-10-20 20:16
@poisa I was trying the "Somewhat stable" UGS Platform. I thought it was the best one.
Now I try the UGS Platform "Normal" and it works ok.
Thank you @winder

**Comment by poisa** [comment] 2017-10-20 20:18
@winder That's great to hear. Will give this a try soon.

**Comment by breiler** [comment] 2018-06-18 06:30
Closing this issue as some of the users now reports that this is fine.

**Closed by breiler** 2018-06-18 06:30 UTC
Labels: bug
