### ISSUE TITLE
Problem with accents for the French language.

### ISSUE THREAD

**Issue by ArtFaks** [winder/Universal-G-Code-Sender#315] opened 2015-11-26 01:45 UTC
Hello, I'm french user and i've a problem with all accentuated characters after select the French language.

I use UGCS version 1.0.9, my OS is Windows 10 and my Java version is 1.8.0_66.

I've also a little problem with "Pendant". When I start the "Pendant" server, no IP is displayed in the console and I can't connect with my iPhone.

See screenshot
![french_accent_bug](https://cloud.githubusercontent.com/assets/399591/11413289/b8ada8fc-93e7-11e5-946c-13163cf04573.jpg)

**Comment by Jibeji** [comment] 2016-05-27 19:34
Hi,
Same issue with version 2.0, there is an encoding problem.

**Comment by winder** [comment] 2016-08-29 17:10
I'm still seeing some strange localization issues with German, but French seems to work fine on an OSX machine.

**Comment by winder** [comment] 2016-08-29 17:58
@ml-hn I'm seeing some errors in POEditor as well. Things like `Schlieu00dfen` instead of `Schließen` can be fixed in the web interface.

There are a couple people who have been working on the German localization recently, if you have time to help you can join here: https://poeditor.com/join/project/2J2hB5I41Z

**Comment by breiler** [comment] 2019-02-20 17:05
Can't reproduce anymore, so I'm closing this.

**Closed by breiler** 2019-02-20 17:05 UTC
