### ISSUE TITLE
UGS Platform Starting Poing Off

### ISSUE THREAD

**Issue by tpaolillo** [winder/Universal-G-Code-Sender#1233] opened 2019-05-08 13:57 UTC
Hi, Im using Windows 7 running UGS Platform. Problem im having is I load my design then Home the CNC and then i set the "Zero" position but when i cut the design the machine always starts about 1/4 inch Y+. For example if i have a 1inch frame around my design, the top will be about 1/4 inch less and bottom 1/4inch more. Very strange. 
I have not edited the code and cant find settings in UGS to stop this. I have triple checked my designs in V-Carve, measurements and they all are perfect.  It does it on ALL of my designs so im assuming the issue is UGS.
Any ideas would help. I attached a screenshot of one of my images i open in UGS. Notice the space at the bottom of the design.
![Capture](https://user-images.githubusercontent.com/50412017/57380595-425dc800-7177-11e9-8dce-482c773a538c.PNG)

Thanks for your help in advance.
Tony

**Comment by tpaolillo** [comment] 2019-05-08 14:24
Here is the two frame files.
[3D Roughing.zip](https://github.com/winder/Universal-G-Code-Sender/files/3157794/3D.Roughing.zip)

**Comment by AbySet** [comment] 2019-05-08 21:22
Can you discribe how to you proceed to set zero position ? Are you doing click on [Reset Zero] button when the machine is on zero position ?
I would like to test your file on my machine but X axis travel is too large for it.

"It does it on ALL of my designs so im assuming the issue is UGS."
Would be helpfull if you attach a smaller design so i can test on my machine (max 13,7 inch X and Y).

**Comment by tpaolillo** [comment] 2019-05-09 01:37
When i set the zero position i move it to the absolute left most corner of the board, So the bit is resting on the board. Then zero out all 3 axis's.

**Comment by AbySet** [comment] 2019-05-09 09:46
I see in your files that the machine is capable of tool changing, so what it your machine ?
(Still looking for solution but walking in the dark, need a machine model).

**Comment by DanielWeigl** [comment] 2019-05-09 09:55
You can verify your gcode here: https://ncviewer.com/

![grafik](https://user-images.githubusercontent.com/1370302/57444605-d059b180-7250-11e9-8db1-58f5ed85ea35.png)

The first move `G0X0.9591Y0.1324Z0.1000` goes to Y0.1324 inch - i guess thats what you are seeing, or? If so, the your gcode is somehow offset.

I never used VCarve, but does it have a Stock-Size setting where it adds a margin around your work pice? (Fusion360 has something like this, which already gave me comparable troubles)

**Comment by tpaolillo** [comment] 2019-05-09 11:37
AbySet i have the BobsCNC G4. It goes 24"x24". Im new at this whole CNC and GCode thing. Im getting pretty good with just a few weeks in. In not familiar with the $101 and $121 settings. I have checked every setting I can find for any preset margins or anything like that. Im going to test this with a different software today to confirm the prob might not be with VCarve.

**Comment by tpaolillo** [comment] 2019-05-09 11:46
Daniel, In this gcode i do have it coming up a bit because i was adding 3D tabs in and it does come up a bit but this one it came up farther then suppose to and cut off the top side of the board about 1/4 inch. Im double checking for all margins in the software but have found nothing. It happens in every cut. 
Note that after the 1/4" move to far up, the rest of the cut is perfect so it seems to point to a margin or a offset of some sort bu i cant find anything.

**Comment by JacksCrafts** [comment] 2019-05-17 07:37
In VCarve you can set an offset. There is a check box you can click on or off.
![DatupOffsetVcarve](https://user-images.githubusercontent.com/44066988/57911153-f8e73a00-7854-11e9-8b67-d6e904e28237.jpg)

**Comment by breiler** [comment] 2019-10-27 08:42
Closing as it seems to be a configuration option in CAM.

**Closed by breiler** 2019-10-27 08:42 UTC
