### ISSUE TITLE
java.lang.NullPointerException on large G-code file

### ISSUE THREAD

**Issue by jhh3000** [winder/Universal-G-Code-Sender#256] opened 2015-05-16 15:39 UTC
Hi,

I'm using the latest UGS (v2.0), built 2015-05-16, and I've been getting these Null Pointer Exception errors that force UGS to close. They happen when I try loading a very large G-code file (around 10,000 instruction). I've increased the maximum memory allowed to 2 GB, but it's still happening. Here's the trace in terminal:

user@Computer: UniversalGcodeSender$ ./start.sh
[Boot] INFO:  myJarPath=file:/Users/user/Downloads/UniversalGcodeSender/UniversalGcodeSender.jar
[JarClassLoader] INFO:  setProperties(com.simontuffs.onejar.JarClassLoader@42ff665a)
[JarClassLoader] INFO:  oneJarPath=file:/Users/user/Downloads/UniversalGcodeSender/UniversalGcodeSender.jar
[Boot] INFO:  using JarClassLoader: com.simontuffs.onejar.JarClassLoader
[JarClassLoader] INFO:  oneJarPath=file:/Users/user/Downloads/UniversalGcodeSender/UniversalGcodeSender.jar
[JarClassLoader] INFO:  resources/build.properties in main/Universal G-Code Sender.jar is hidden by / (with different bytes)
[JarClassLoader] INFO:  findResource() found: "com/willwinder/universalgcodesender/utils/Version.class" for caller null in codebase main/Universal G-Code Sender.jar
[JarClassLoader] INFO:  findResource(): unable to locate "resources/MessagesBundle_en.properties"
May 16, 2015 11:35:35 AM com.willwinder.universalgcodesender.utils.SettingsFactory loadSettings
INFO: Loading settings.
May 16, 2015 11:35:35 AM com.willwinder.universalgcodesender.utils.SettingsFactory loadSettings
INFO: Settings file location: /Users/user/Library/Preferences/UniversalGcodeSender.json
May 16, 2015 11:35:36 AM com.willwinder.universalgcodesender.model.GUIBackend applySettings
INFO: Applying settings.
May 16, 2015 11:35:36 AM com.willwinder.universalgcodesender.model.GUIBackend addControllerListener
INFO: Adding controller listener.
May 16, 2015 11:35:36 AM com.willwinder.universalgcodesender.model.GUIBackend addControlStateListener
INFO: Adding control state listener.
May 16, 2015 11:35:38 AM com.willwinder.universalgcodesender.model.GUIBackend connect
INFO: Connecting to GRBL on port /dev/tty.usbmodemfd121
May 16, 2015 11:35:38 AM com.willwinder.universalgcodesender.model.GUIBackend sendControlStateEvent
INFO: Sending control state change.
May 16, 2015 11:35:44 AM com.willwinder.universalgcodesender.model.GUIBackend sendControlStateEvent
INFO: Sending control state change.
May 16, 2015 11:35:45 AM com.willwinder.universalgcodesender.model.GUIBackend disconnect
INFO: Disconnecting.
May 16, 2015 11:35:45 AM com.willwinder.universalgcodesender.model.GUIBackend sendControlStateEvent
INFO: Sending control state change.
May 16, 2015 11:35:45 AM com.willwinder.universalgcodesender.model.GUIBackend connect
INFO: Connecting to GRBL on port /dev/tty.usbmodemfd121
May 16, 2015 11:35:45 AM com.willwinder.universalgcodesender.model.GUIBackend sendControlStateEvent
INFO: Sending control state change.
May 16, 2015 11:35:48 AM com.willwinder.universalgcodesender.model.GUIBackend send
INFO: Sending gcode file.
May 16, 2015 11:35:48 AM com.willwinder.universalgcodesender.model.GUIBackend isConnected
INFO: Is connected: true
May 16, 2015 11:35:48 AM com.willwinder.universalgcodesender.model.GUIBackend sendControlStateEvent
INFO: Sending control state change.
java.lang.NullPointerException
	at com.willwinder.universalgcodesender.AbstractController.commandSent(AbstractController.java:627)
	at com.willwinder.universalgcodesender.AbstractCommunicator.sendEventToListener(AbstractCommunicator.java:194)
	at com.willwinder.universalgcodesender.AbstractCommunicator.dispatchListenerEvents(AbstractCommunicator.java:177)
	at com.willwinder.universalgcodesender.GrblCommunicator.streamCommands(GrblCommunicator.java:152)
	at com.willwinder.universalgcodesender.GrblCommunicator.responseMessage(GrblCommunicator.java:203)
	at com.willwinder.universalgcodesender.connection.JSSCConnection.serialEvent(JSSCConnection.java:132)
	at jssc.SerialPort$LinuxEventThread.run(SerialPort.java:1299)
May 16, 2015 11:35:49 AM com.willwinder.universalgcodesender.utils.SettingsFactory saveSettings
INFO: Saving settings.
May 16, 2015 11:35:49 AM com.willwinder.universalgcodesender.utils.SettingsFactory saveSettings
INFO: Saving settings.

**Comment by winder** [comment] 2015-06-10 12:31
Duplicate of #214

**Closed by winder** 2015-06-10 12:31 UTC
Labels: bug, duplicate
