### ISSUE TITLE
Java lang null exception.  Load gcode file from Carveco into UGS 2.0.9 I can toggle machinex,y and z when I send file I get java.lang.NullPointerException error

### ISSUE THREAD

**Issue by Daryldink** [winder/Universal-G-Code-Sender#1765] opened 2022-01-11 21:15 UTC
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Version**
[e.g. UGS Platform 2.0.6, UGS Classic 1.0.9]

**Hardware**
[e.g. GRBL 1.1f, TinyG,  SmoothieBoard]

**Operating system (please complete the following information):**
 [e.g. Windows 10, MacOSX, Ubuntu 20.04 ]

**Additional context**

**Comment by breiler** [comment] 2022-01-12 06:19
Closing as it looks like a duplicate of #1759

**Closed by breiler** 2022-01-12 06:19 UTC
Labels: duplicate
