### ISSUE TITLE
UGS 2.1.2 sees empty folders in MacOS Catalina

### ISSUE THREAD

**Issue by pmap1993** [winder/Universal-G-Code-Sender#2383] opened 2023-12-08 13:25 UTC
### Version

2.1.2

### Hardware / Firmware

GRBL 1.1

### What happened

Good day, UGS works well when it's the older version, but I decided to use the newer version today.

I had given Full Disk Access in the Security part of Settings and this is what I see. Screenshot below:
![Screen Shot 2023-12-08 at 9 20 55 PM](https://github.com/winder/Universal-G-Code-Sender/assets/153291790/569b2f8a-40ff-4530-80a6-e3e18bc2384f)

Please note that the version 2.0.20 is perfectly fine! Screenshot below:
![Screen Shot 2023-12-08 at 9 23 27 PM](https://github.com/winder/Universal-G-Code-Sender/assets/153291790/3136493f-f925-4a4b-ae46-099d0edef2c1)

This is a newly reformatted laptop, I'm using an old 2012 MacBook for CNC only.
Is there something wrong with my program? or I have done something wrong?

### How to reproduce

Use the Open File dialog using latest version 2.1.

### Operating System

macOS Catalina 10.15.7

### Anything else

Older version 2.0.20 didn't even need to have Full Disk Access to be set and it works fine.

**Comment by pmap1993** [comment] 2023-12-08 13:28
UGS 2.1 with Full Disk Access.

![Screen Shot 2023-12-08 at 9 26 38 PM](https://github.com/winder/Universal-G-Code-Sender/assets/153291790/3f1bd889-358f-4cb6-8baf-7e31f7c052d1)

**Comment by breiler** [comment] 2023-12-08 13:32
Can you start UGS 2.1.2, click on the menu `Tool -> Open log directory` and then drag the `messages.log` file to github.

**Comment by breiler** [comment] 2023-12-08 13:37
Never mind, I managed to reproduce the error. I am looking into what happened.

**Comment by pmap1993** [comment] 2023-12-09 14:22
> Please try the latest nightly build here:
> https://github.com/winder/Universal-G-Code-Sender#downloads

Sorry for the delay, it gave a similar issue:
![Screen Shot 2023-12-09 at 10 21 42 PM](https://github.com/winder/Universal-G-Code-Sender/assets/153291790/3cfef5d4-668d-483f-a008-02f2b583c6e6)

I wonder why.
I deleted all UGS versions for this Nightly Build test.
Also provided Full Disk Access for this build as well..

**Comment by pmap1993** [comment] 2023-12-12 10:41
If it makes a difference, when using UGS 2.0 for the first time (like a new download) in Mac, it asks 'it would like to access your Desktop folder'.. compared to the latest one where it does not.

**Comment by breiler** [comment] 2023-12-12 11:04
> I do apologize for the long post

No need to apologize, thanks for taking your time testing.

I booted up my old iMac and I was able to reproduce the problem. I have read about other Java based programs that experience the same problem. This seems to be a bug either in the access rights system in MacOSX or in the integration with Java.

I don't think that we can do much about this. You will simply have to place the files in a sub directory in your home folder. =(

**Comment by pmap1993** [comment] 2023-12-12 11:08
> > I do apologize for the long post
> 
> No need to apologize, thanks for taking your time testing.
> 
> I booted up my old iMac and I was able to reproduce the problem. I have read about other Java based programs that experience the same problem. This seems to be a bug either in the access rights system in MacOSX or in the integration with Java.
> 
> I don't think that we can do much about this. You will simply have to place the files in a sub directory in your home folder. =(

Thank you for trying to update it

**Comment by breiler** [comment] 2023-12-17 06:51
I am closing this as there is nothing we can do about it. 

Sorry.

**Closed by breiler** 2023-12-17 06:51 UTC
