### ISSUE TITLE
$X 

### ISSUE THREAD

**Issue by vMeph** [winder/Universal-G-Code-Sender#523] opened 2016-11-01 15:28 UTC
will it be any update on the way $X works?
dont know why when u start machine and you unlock alarm($X)
i cant acess comand actions panel or eaven send file to start, unless i go to jog controler and make machine to make a movement and then i got acess to the panels
dont know if this is a bug or if this is the way its going to be, at least i dont see no sense in this way of working, the way it was on previous version like 652 was way better
is this on the list to be fix or will it keep this way?

**Comment by winder** [comment] 2016-11-01 18:32
Duplicate of #522

**Closed by winder** 2016-11-01 18:32 UTC
Labels: duplicate
