### ISSUE TITLE
Visualizer on Lubuntu doesn't show anything.

### ISSUE THREAD

**Issue by lolobosse** [winder/Universal-G-Code-Sender#206] opened 2014-12-04 17:37 UTC
Step to reproduce:
 - Start the UGS8/7 on Lubuntu 14 with Terminal
 - Load a file.
 - Clic on visualize and it should start a window of visualization totally black.

It has already been reported but, not being solved. It's mentionned there:
 - http://www.shapeoko.com/forum/viewtopic.php?f=6&t=3094&start=10 (response from ajacocks)

I think this issue could be solved with an update of the gluegen library (the last was 2 years ago). I need to test to update it but my machine is all new and I have no Eclipse on it yet :(

**Comment by winder** [comment] 2015-02-24 18:42
I updated the java OpenGL library, if you try the latest nightly could you let me know if its working for you?

**Comment by winder** [comment] 2015-02-24 18:47
duplicate of #187

**Closed by winder** 2015-02-24 18:47 UTC
Labels: bug, duplicate

**Comment by lolobosse** [comment] 2015-02-24 23:31
Yes! :+1: Thanks! My CNC will work alone yet, it was the last step. :sparkles: :pray:
