### ISSUE TITLE
Reset axis treated as job 

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#547] opened 2016-11-20 15:39 UTC
You have to hit the stop button after resetting an axis to be able to reset the other or do anything else.

**Comment by winder** [comment] 2016-11-20 16:36
Thanks, it looks like any commands which complete instantly are causing problems.

**Comment by breiler** [comment] 2018-07-15 17:32
Can not reproduce this, it's has been fixed right?

**Comment by breiler** [comment] 2018-07-25 04:59
Closing as I'm no longer able to reproduce the issue.

**Closed by breiler** 2018-07-25 04:59 UTC
Labels: bug
