### ISSUE TITLE
Entering values in Inches sends measurements in mm.

### ISSUE THREAD

**Issue by sfmissionmark** [winder/Universal-G-Code-Sender#2429] opened 2024-01-16 22:37 UTC
### Version

2.1.4

### Hardware / Firmware

GRBL 1.1

### What happened

Manually entering values via ui set buttons sends values as mm regardless of if you are in inch mode or mm mode.

### How to reproduce

Click value on X axis. Add value in inches. New value reflects mm.

### Operating System

ubuntu

**Comment by sfmissionmark** [comment] 2024-01-16 22:37
I verified this behavior on todays nightly build.

**Comment by breiler** [comment] 2024-01-17 06:29
Can you give me 
* Your settings from `$$`
* Your gcode parser state `$G`
* And your build version `$I`

**Comment by breiler** [comment] 2024-01-22 20:01
Closing as I can't reproduce and did not get more information from user.

**Closed by breiler** 2024-01-22 20:01 UTC
