### ISSUE TITLE
Platform crashing after starting

### ISSUE THREAD

**Issue by olsarge03** [winder/Universal-G-Code-Sender#1079] opened 2018-07-12 16:50 UTC
[hs_err_pid8928.log](https://github.com/winder/Universal-G-Code-Sender/files/2189490/hs_err_pid8928.log)

I have attached the error log. The classic build is working fine. Only the platform gui is crashing after starting. Previous platform nightly releases was working. I don't update often so the build that was working is probably from a month ago.

**Comment by breiler** [comment] 2018-07-14 05:35
We can start with upgrading your Java from version 1.8.0_141 which is about a year old.
You can find a new version here: https://java.com/en/download/manual.jsp

**Comment by olsarge03** [comment] 2018-07-15 18:54
Java said I was running the most current version. But I uninstalled and reinstalled Java. It is still crashing.
![java version](https://user-images.githubusercontent.com/30358396/42737247-9d488230-8836-11e8-8ae1-14d33c268999.jpg)
[hs_err_pid9428.log](https://github.com/winder/Universal-G-Code-Sender/files/2196005/hs_err_pid9428.log)

**Comment by olsarge03** [comment] 2018-07-17 16:20
new nightly, error log shows latest version of java, still crashing
[hs_err_pid12136.log](https://github.com/winder/Universal-G-Code-Sender/files/2202490/hs_err_pid12136.log)

**Comment by zbuckholz** [comment] 2018-07-23 17:06
I am having the same issue, just decided to download latest and check out what's new. 

It worked once, it showed me the new startup screen, I clicked the box telling it not to show again. Then closed the app, and reopened it. Now it just crashes as soon as it launches and shows the nightly build popup box.

[hs_err_pid14415.log](https://github.com/winder/Universal-G-Code-Sender/files/2220309/hs_err_pid14415.log)

**Comment by breiler** [comment] 2020-10-02 19:49
Not able to reproduce and no one else has reported similar issues. Closing.

**Closed by breiler** 2020-10-02 19:49 UTC
