### ISSUE TITLE
Visualizer black screen

### ISSUE THREAD

**Issue by fredkylam** [winder/Universal-G-Code-Sender#224] opened 2015-02-10 01:21 UTC
Visualizer runs perfectly under Windows os  but shows black screen under Ubuntu 12.04

**Comment by winder** [comment] 2015-02-11 13:37
Have you enabled the proprietary graphics driver for your Ubuntu installation?

**Comment by fredkylam** [comment] 2015-02-11 18:03
Hi Will
Thanks for your quick response.
No, the system does not report any proprietary drivers. It does indicate
that an unknown driver is used for graphics.

On Wed, Feb 11, 2015 at 5:37 AM, Will Winder <notifications@github.com>
wrote:

> Have you enabled the proprietary graphics driver for your Ubuntu
> installation?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/winder/Universal-G-Code-Sender/issues/224#issuecomment-73881630>
> .
>



-- 
Fred Lam

**Comment by winder** [comment] 2015-02-24 18:04
I updated the OpenGL library in UGS, could you give the latest nightly build a try and see if that fixed the problem?

**Comment by winder** [comment] 2015-02-24 18:46
duplicate of #187

**Closed by winder** 2015-02-24 18:46 UTC
Labels: bug, duplicate

**Comment by fredkylam** [comment] 2015-02-24 21:55
Yes, problem solved. Thank you.

On Tue, Feb 24, 2015 at 10:47 AM, Will Winder <notifications@github.com>
wrote:

> Closed #224 <https://github.com/winder/Universal-G-Code-Sender/issues/224>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/winder/Universal-G-Code-Sender/issues/224#event-241144192>
> .
>



-- 
Fred Lam
