### ISSUE TITLE
BUG: Upgrade from 2.0.9 to 2.0.11  - settings

### ISSUE THREAD

**Issue by daxliniere** [winder/Universal-G-Code-Sender#1837] opened 2022-03-21 15:56 UTC
### Version

Other

### Hardware / Firmware

GRBL 1.1

### What happened

Extracted 2.0.11 over 2.0.9 and GUI layout was not as it had been before. I imported my settings from 2.0.9 but it didn't fix anything.

More importantly, the Toolbox was showing the default buttons. I went into Options>UGS>Toolbox and all buttons were correctly listed!
So, I then went to the Macros tab, at which point the Toolbox in the main GUI window refreshed and now displays the buttons correctly.

It's possible that importing my settings wasn't a necessary step (but it's what I did).

### How to reproduce

See above.

### Operating System

Win10x64 Pro N

**Comment by breiler** [comment] 2022-03-22 05:44
Duplicate of #1781

**Closed by breiler** 2022-03-22 05:44 UTC
Labels: duplicate
