### ISSUE TITLE
Z Plane (YZ) Arc problem

### ISSUE THREAD

**Issue by dustnnotes** [winder/Universal-G-Code-Sender#1154] opened 2018-11-27 16:03 UTC
## Problem description 
 Arc's in the YZ plane do not appear to be implemented correctly.  I need to translate an object from the XY to the YZ planes for an operation on my CNC machine.  I was successful in developing my G-code translation algorithm, as confirmed by proper operation of a different sender (OpenBuilds), but was never successful in getting UGS to properly visualize/send the translated G-code.

### Expected Behavior

Arcs in YZ plane behave the same as those in XY plane

### Actual Behavior

G0/G1 commands ported from XY to YZ planes are reproduced accurately, G2/G3 commands are not..

### Steps to Reproduce the Problem

1. So far as I can tell, try any G2 or G3 command in a Z plane (I have focused on YZ, but believe it occurs in XZ as well).

2 .Here is an object G-code in XY that includes arcs:
[R_XY.txt](https://github.com/winder/Universal-G-Code-Sender/files/2620858/R_XY.txt)

Here is the UGS Visualizer in XY:
![ugs xy screenshot](https://user-images.githubusercontent.com/8951422/49094784-e8e28c00-f21b-11e8-9f8d-daf746f84851.png)

 3. Here is the same object G-code, translated to YZ:
 [R_YZ.txt](https://github.com/winder/Universal-G-Code-Sender/files/2620859/R_YZ.txt)

And the result in UGS Visualizer in YZ:
![ugs yz screenshot](https://user-images.githubusercontent.com/8951422/49094888-22b39280-f21c-11e8-82d3-470ba452f336.png)

4. As a reference, I used a different sender (OpenBuilds), and the Z-plane operation worked fine on my CNC machine.

#### Version

UGS Platform 2.0.0 Stable

#### Operating system

Windows (both 7 and 10)

#### Platform

GRBL 1.1f, in a Workbee CNC machine with Laser attachment.  Translation is required to enable engraving on the side of a work piece.

**Comment by dastultz** [comment] 2018-11-27 16:22
There's pretty little to go on here, but this might be a duplicate of https://github.com/winder/Universal-G-Code-Sender/issues/853

**Comment by dustnnotes** [comment] 2018-11-27 16:33
Thanks for the quick response @dastultz!
Sorry, I had an issue uploading the G-code the first time, posted now.  I took a look at #853, but wasn't sure, and wanted to provide my case as well.  This is a blocking issue for me on this for operation, and I would rather not use multiple senders.

**Comment by AbySet** [comment] 2018-11-28 07:32
I tested it even with 11.25.2018 version nightly build and confirm the issue.

Tested under:
-Windows 10 x64
- Java 8.191.

**Comment by dastultz** [comment] 2018-11-28 19:50
Yes, sorry, I meant to mention disabling Arc Expander. Couldn't remember if I enabled it or disabled it as a work around.

**Comment by DanielWeigl** [comment] 2019-04-26 21:46
This looked like a nice bug to get to know the codebase a bit better.. Looked into it and I think I found it, fixed in https://github.com/winder/Universal-G-Code-Sender/pull/1220

Tested against robomechs and dustnnotes GCode:    
![grafik](https://user-images.githubusercontent.com/1370302/56838174-5b17d500-687d-11e9-8de1-d066c4d8afe5.png)

![grafik](https://user-images.githubusercontent.com/1370302/56838198-71be2c00-687d-11e9-94dc-6985b7200998.png)

**Comment by dastultz** [comment] 2019-04-28 00:15
Awesome, I'll try to confirm after merge. Thanks.

**Closed** 2019-04-29 12:46 UTC
Labels: bug
