### ISSUE TITLE
Keyboard Movement active in file open dialogue

### ISSUE THREAD

**Issue by typ-o** [winder/Universal-G-Code-Sender#266] opened 2015-06-23 09:28 UTC
Hi!

If I'm going to load a new file, and try to navigate through the files shown in file open dialogue, any cursor usage will move the machine. This is dangerous. 

/UniversalGcodeSender-v1.0.8/UniversalGcodeSender.jar
Native lib Version = RXTX-2.1-7
Java lib Version   = RXTX-2.1-7

Thank you for Your work, I'm happy to use UGCS!

**Comment by jahnj0584** [comment] 2016-09-28 01:16
Is this still an issue? I dont think it is.

**Comment by breiler** [comment] 2018-07-27 10:43
Yes this is still an issue with the classic version when keyboard movement is active.

**Comment by breiler** [comment] 2020-04-10 04:32
Duplicate of #124

**Closed by breiler** 2020-04-10 04:32 UTC
Labels: bug
