### ISSUE TITLE
Can't reset window layout on mac Version 2.0 Nightly 3-9-20

### ISSUE THREAD

**Issue by lorenrogers** [winder/Universal-G-Code-Sender#1371] opened 2020-03-22 03:49 UTC
## Problem description 
`Window > Reset Windows` does not work. Two error messages appear.

![Screen Shot 2020-03-21 at 11 42 21 PM](https://user-images.githubusercontent.com/1090824/77241810-f4ef1b80-6bcd-11ea-83ad-13bd15f055df.png)

### Expected Behavior
When I run reset windows, the app is reset to the default layout I had when the app was first installed.

### Actual Behavior
Error messages are shown (see below) and the windows are unchanged.

### Steps to Reproduce the Problem
1. Open the app
1. "Delete" a window by clicking the x
1. Click `Window > Reset Windows`

#### Version
UGS Platform 2.0 - Nightly Build Mar 9, 2020

#### Operating system

![Screen Shot 2020-03-21 at 11 44 23 PM](https://user-images.githubusercontent.com/1090824/77241806-e7399600-6bcd-11ea-986a-d05664b37670.png)

**Comment by breiler** [comment] 2020-03-22 14:52
Could you attach your log file:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#log-files

**Comment by lorenrogers** [comment] 2020-03-22 16:17
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/4365570/messages.log)

**Comment by lorenrogers** [comment] 2020-03-22 16:34
Also, it's worth noting that the path is different from what's on the wiki: `~/Library/Application Support/ugsplatform/2.0-SNAPSHOT/dev/var/log`

**Comment by breiler** [comment] 2022-01-14 06:38
Sorry about the delayed response. According to the log the program is missing a bunch of files. Got deleted somehow?
Reinstall and try again.

(Closing as the issue is really old)

**Closed by breiler** 2022-01-14 06:38 UTC
