### ISSUE TITLE
Inches instead of millimeters​

### ISSUE THREAD

**Issue by waltoncnc** [winder/Universal-G-Code-Sender#1054] opened 2018-06-12 22:31 UTC
Is there any plans to get inches working?
Platform nightly builds.
 Windows 7
Grbl 1.1

**Comment by breiler** [comment] 2018-06-13 04:55
Duplicate of #1038 

We'll try to fix this as soon as we've got the time.

**Closed by breiler** 2018-06-13 04:55 UTC
Labels: duplicate
