### ISSUE TITLE
program still running when $4=1

### ISSUE THREAD

**Issue by kweilim98** [winder/Universal-G-Code-Sender#1891] opened 2022-05-29 17:13 UTC
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

when the $4=1, mean all the axis motor already been enable, but the program still running and non stop 

### Operating System

cnc grbl

**Comment by breiler** [comment] 2022-05-29 17:17
I don't understand what you mean, please elaborate.

**Comment by kweilim98** [comment] 2022-05-29 17:24
when $4 is enable , mean all the axis motor will be enable when detect the current cut off when g-code is running. but the g-code program still running and not hold

**Comment by kweilim98** [comment] 2022-05-29 17:29
because I am using the door switch and connected to a relay. When the door is open, all axis motor and spindle will be enabled, but the g-code program not freeze

**Comment by breiler** [comment] 2022-05-29 17:36
The $4 setting is just for inverting the step enable pin and to my knowledge does not have anything to do with the door state.

But you might be right that UGS doesn't recognise the door state from the controller and will keep streaming commands. This requires some experimentation.

**Comment by kweilim98** [comment] 2022-05-29 17:41
Will UGS focus on this feature to stop the command continues streaming? Because I already try on that and found that have problem on there. Hope the author can upgrade or add-on on there. thx u.

**Comment by breiler** [comment] 2023-02-23 19:33
Just tested this, UGS recognizes/reads the door switch, enters a HOLD state and pauses any running gcode program.
Closing as I can't reproduce the error.

**Closed by breiler** 2023-02-23 19:33 UTC
