### ISSUE TITLE
UGS Screen Freeze and/or close out

### ISSUE THREAD

**Issue by Username-CNC** [winder/Universal-G-Code-Sender#2413] opened 2024-01-02 14:50 UTC
### Version

2.0.11

### Hardware / Firmware

GRBL 1.1

### What happened

Execution
2.0.11
The problem also exists with version 2.1.2

Hardware/Firmware
GRBL 1.1

What happened:
When running the 64-bit module, the program exits on its own without any warning or error code. The spindle continues to run endlessly. I went into ugsplatform.conf and changed the value of Xms from 64 to 512. This had no effect on the problem I'm having. I tried running the 32 bit version and it will complete the project. However, the program would freeze during the project and all buttons would become unresponsive. I would have to quit the program.

How to reproduce
This problem can be easily reproduced on my computer.

operating system
Notebook Fujitsu
Windows 10 Home version 22H2
64-bit operating system
8GB RAM
Intel graphics

Something else
I use Vectric Vcarve Pro.

### Anything else

The problem occurs every time

**Comment by breiler** [comment] 2024-01-02 14:54
Can you post the log file:
C:/Users/[your username>]/AppData/Roaming/ugsplatform/var/log/messages.log

**Comment by Username-CNC** [comment] 2024-01-02 14:57
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/13811092/messages.log)
[messages_1.log](https://github.com/winder/Universal-G-Code-Sender/files/13811093/messages_1.log)
[messages_2.txt](https://github.com/winder/Universal-G-Code-Sender/files/13811094/messages_2.txt)

**Comment by breiler** [comment] 2024-01-02 15:14
I am not sure, but it looks like you are using the 32-bit version of UGS in these logs and you can very well hit the 2Gb memory limit, that is probably why the program becomes unresponsive. I would like a log file from the 64-bit edition, make sure that you have downloaded a 64-bit package:
https://universalgcodesender.com/download/

I noticed that it takes fairly long to load the model and that it contains some parsing warnings. Is it a big file? Do mind sharing one?

**Comment by Username-CNC** [comment] 2024-01-02 16:02
[raphael-3D Schlichten 1.zip](https://github.com/winder/Universal-G-Code-Sender/files/13811666/raphael-3D.Schlichten.1.zip)

**Comment by breiler** [comment] 2024-01-02 16:16
I had no problems loading the file but noticed that it requires quite alot memory - around 2.2Gb on my system. So make sure that you've downloaded the 64-bit packaging of UGS.

**Comment by Username-CNC** [comment] 2024-01-02 16:19
I will test everything again tomorrow with the 64 bit 2.1.3 version and send you the log file. Thank you for your quick message

**Comment by Username-CNC** [comment] 2024-01-03 16:21
I recently carried out the test again, unfortunately UGS freezes after a short time. See messages.log
I have the feeling that the cause is to be found in the spindle motor. Do you know this problem?
[messages.log](https://github.com/winder/Universal-G-Code-Sender/files/13821204/messages.log)
[messages_1.log](https://github.com/winder/Universal-G-Code-Sender/files/13821205/messages_1.log)

**Comment by breiler** [comment] 2024-01-03 18:44
Very strange, it still says that it can use maximum 2Gb.

Can you open the config file `C:\Program Files\ugsplatform-win\etc\ugsplatform.conf` and add the parameter `-J-Xmx4G`.

This should force a increase of the memory to 4Gb.

**Comment by breiler** [comment] 2024-01-23 18:49
Closing as we got no further response from user and I can't reproduce the problem.

**Closed by breiler** 2024-01-23 18:49 UTC
