### ISSUE TITLE
Reset visualizer lines after M30/File end

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#834] opened 2017-12-03 14:05 UTC

**Comment by dastultz** [comment] 2017-12-03 14:25
I think I noticed this myself recently. I run "check" first after which all the lines show as having been run. Then I run my program with everything looking like it's all done. It's on my list to take a look at.

I was planning on resetting the lines upon start of the run. I don't feel strongly about it either way.

**Comment by winder** [comment] 2017-12-03 14:58
Duplicate of #593

**Closed by winder** 2017-12-03 14:58 UTC
