### ISSUE TITLE
"Error while starting filestream: null"

### ISSUE THREAD

**Issue by villamany** [winder/Universal-G-Code-Sender#214] opened 2015-01-20 14:51 UTC
Hi, thanks for the great work!.

Im getting this error on 1.0.8 (nightly) and previous versions.
Mainly at beggining but some times on middle of a work.

Im using windows 7 x86. This is the log: 

![image](https://cloud.githubusercontent.com/assets/5514002/5819180/0a2cc7e6-a0bc-11e4-82ba-144ab5c84979.png)

[verbose]<Idle,MPos:0.000,0.000,0.000,WPos:0.000,0.000,0.000>
[verbose]<Idle,MPos:0.000,0.000,0.000,WPos:0.000,0.000,0.000>
[verbose]<Idle,MPos:0.000,0.000,0.000,WPos:0.000,0.000,0.000>
[verbose]<Idle,MPos:0.000,0.000,0.000,WPos:0.000,0.000,0.000>
Skipping command #0
>>> M5
Skipping command #2
>>> G21G90
>>> G0Z11.5
ok
Skipping command #5
>>> G17
>>> G0X0.0Y0.0
>>> Z0.1
>>> G1S1.0F30000.0
ok
ok
ok
>>> S0M3
>>> Y44.0568S124.3333F1000.0
>>> X0.1292
ok
ok
ok
ok
>>> X0.2584
>>> X0.3876
>>> X0.5168
>>> X0.646
>>> X0.7752
>>> X0.9044
>>> X1.0336
>>> X1.1628
>>> X1.292S141.0
ok
>>> X1.4212S124.3333
>>> X1.5504
>>> X1.6796
ok
>>> X1.8088
ok
>>> X1.938
ok
>>> X2.0672
ok
>>> X2.1964
ok
>>> X2.3256
ok
>>> X2.4548
ok
>>> X2.584
ok
>>> X2.7132
ok
>>> X2.8424
ok
>>> X2.9716
>>> X3.1008
ok
>>> X3.23
>>> X3.3592
ok
>>> X3.4884
ok
>>> X3.6176S141.0
>>> X3.7468S124.3333
ok
ok
ok
ok
>>> X3.876
ok
>>> X4.0052
ok
>>> X4.1344
ok
>>> X4.2636
ok
>>> X4.3928
ok
>>> X4.522
ok
>>> X4.6512
ok
>>> X4.7804
ok
>>> X4.9096
ok
>>> X5.0388
ok
>>> X5.168
ok
>>> X5.2972
>>> X5.4264
[verbose][Error] Command <X5.4264> does not equal expected command <X5.2972>[verbose][Error] Command <X5.2972> does not equal expected command <X5.4264>ok
>>> X5.6848
>>> X5.5556
[verbose][Error] Command <X5.5556> does not equal expected command <X5.6848>ok
>>> X5.814
[verbose][Error] Command <X5.6848> does not equal expected command <X5.814>ok
>>> X5.9432
[verbose][Error] Command <X5.814> does not equal expected command <X5.9432>ok
>>> X6.0724
[verbose][Error] Command <X5.9432> does not equal expected command <X6.0724>ok
>>> X6.2016
[verbose][Error] Command <X6.0724> does not equal expected command <X6.2016>ok
>>> X6.3307
[verbose][Error] Command <X6.2016> does not equal expected command <X6.3307>ok
>>> X6.4599
[verbose][Error] Command <X6.3307> does not equal expected command <X6.4599>ok
>>> X6.5891
[verbose][Error] Command <X6.4599> does not equal expected command <X6.5891>ok
>>> X6.7183
[verbose][Error] Command <X6.5891> does not equal expected command <X6.7183>ok
>>> X6.8475
[verbose][Error] Command <X6.7183> does not equal expected command <X6.8475>ok
>>> X6.9767
[verbose][Error] Command <X6.8475> does not equal expected command <X6.9767>ok
>>> X7.1059
[verbose][Error] Command <X6.9767> does not equal expected command <X7.1059>ok
>>> X7.2351
[verbose][Error] Command <X7.1059> does not equal expected command <X7.2351>ok

...Same error many times then...

[verbose][Error] Command <X12.9199> does not equal expected command <X40.4393>ok
ok
>>> X40.3101S74.3333
[verbose][Error] Command <X12.7907> does not equal expected command <X40.3101S74.3333>ok
ok
>>> X40.1809S57.6667
>>> X40.0517
[verbose][Error] Command <X12.6615S191.0> does not equal expected command <X40.1809S57.6667>error: Invalid gcode ID:25
>>> X39.9225
[verbose][Error] Command <X12.5323> does not equal expected command <X39.9225>ok
>>> X39.7933S74.3333
ok
>>> X39.6641S57.6667
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X39.5349
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X39.4057S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X39.2765
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X39.1473S57.6667
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X39.0181S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X38.8889
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X38.7597S57.6667
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X38.6305S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X38.5013
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X38.3721S57.6667
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X38.2429S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X38.1137
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.9845
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.8553S57.6667
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.7261S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.5969
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.4677
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.3385
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.2093
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X37.0801
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.9509
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.8217
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.6925
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.5633
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.4341
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.3049
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.1757
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X36.0465
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.9173
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.7881S91.0
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.6589S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.5297
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.4005S91.0
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.2713S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.1421
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X35.0129
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X34.8837
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X34.7545S91.0
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X34.6253S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X34.4961
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X34.3669
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X34.2377S91.0
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X34.1085S74.3333
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X33.9793
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X33.8501
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X33.7209
[verbose][Error] Error while processing response <ok>: Attempting to complete a command that doesn't exist: <(-1)>ok
>>> X33.5917

..Continue this error....

**Comment by xkobalx** [comment] 2015-01-31 01:14
I'm getting the same issue. Here is what I was able to capture from the console.
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9436 >= 7078
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$59.run(MainWindow.java
:2706)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9437 >= 7079
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$58.run(MainWindow.java
:2684)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9437 >= 7079
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$59.run(MainWindow.java
:2706)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9438 >= 7080
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$58.run(MainWindow.java
:2684)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9438 >= 7080
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$59.run(MainWindow.java
:2706)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9439 >= 7081
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$58.run(MainWindow.java
:2684)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9439 >= 7081
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$59.run(MainWindow.java
:2706)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9440 >= 7082
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$58.run(MainWindow.java
:2684)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9440 >= 7082
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$59.run(MainWindow.java
:2706)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9441 >= 7083
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$58.run(MainWindow.java
:2684)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9441 >= 7083
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$59.run(MainWindow.java
:2706)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9442 >= 7084
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$58.run(MainWindow.java
:2684)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException:
 9442 >= 7084
        at java.util.Vector.elementAt(Unknown Source)
        at javax.swing.table.DefaultTableModel.getValueAt(Unknown Source)
        at com.willwinder.universalgcodesender.uielements.GcodeTable.updateRow(G
codeTable.java:105)
        at com.willwinder.universalgcodesender.MainWindow$59.run(MainWindow.java
:2706)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Sour
ce)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by jhh3000** [comment] 2015-05-16 15:41
I just started a new issue thread called "java.lang.NullPointerException on large G-code file" but I've tried re-running my G-code file a few times and have received this exact same error. Perhaps these two are related?

Link: https://github.com/winder/Universal-G-Code-Sender/issues/256

**Comment by VincentGijsen** [comment] 2015-05-31 15:47
same issue here, a code file (rasterized image), 1385696 rows

**Comment by winder** [comment] 2015-06-03 21:10
I think there is a timing issue, I made a performance improvement in the nightly build recently which seems to exacerbate the issue -- so I'm able to reproduce the problem now.

I think somehow one of the command buffer is being exhausted before the file is done being sent. I probably could change the lists to be something like a blocking queue to resolve the problem. Its a timing problem though, so as soon as I try to set a breakpoint to see the issue happen things are magically fixed.

On my computer enabling the "scroll output window" option slows things down just enough for the timing issue to dissapear...

**Comment by winder** [comment] 2015-06-10 12:40
I believe this issue should be resolved in the current nightly build. Some of the data structures needed to be changed to thread safe versions. My guess is that this has always been an issue but it was only recently exposed due to all the performance improvements made to GRBL over the past year.

Let me know if you still see these problems.

**Comment by VincentGijsen** [comment] 2015-06-10 13:06
indeed, using a nightly build resolves big files crashing the app, nice
work!

2015-06-10 14:40 GMT+02:00 Will Winder <notifications@github.com>:

> I believe this issue should be resolved in the current nightly build. Some
> of the data structures needed to be changed to thread safe versions. My
> guess is that this has always been an issue but it was only recently
> exposed due to all the performance improvements made to GRBL over the past
> year.
>
> Let me know if you still see these problems.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/winder/Universal-G-Code-Sender/issues/214#issuecomment-110734290>
> .
>



-- 
Met vriendelijke groet,

Vincent Gijsen
http://www.vincentgijsen.nl

**Comment by jhh3000** [comment] 2015-06-11 00:41
It definitely improves reliability; however I was testing a file on Grbl v 0.9i and it seems to have crashed at the very last instruction in the set (a return to zero command). It throws the error message "attempting to complete a command that doesn't exist" and gives me the last command in the file (G90 G28 X0 Y0). But the strange thing is, when I poll Grbl for the controller state, I get 0, 0, 0 which means that Grbl must have received the command...

**Closed** 2015-07-16 14:23 UTC
Labels: bug

**Comment by klucsik** [comment] 2018-11-30 17:06
This issue is just happend to me on my raspberi pi, i turned off the croll outut window and the UGS is working.
