### ISSUE TITLE
Visualization Issue

### ISSUE THREAD

**Issue by barnold96** [winder/Universal-G-Code-Sender#333] opened 2016-01-21 21:11 UTC
Since I work with inches, I changed UGS to report inches - $13=1 recently.  When running a job, inches are reported on the main window for X,Y,Z but the visualization is plotting in mm, apparently.  The tool icon barely moves; all the other visualization looks normal.

**Comment by winder** [comment] 2016-01-22 15:40
This is a known limitation to how the visualizer was implemented, basically the drawing code converts everything to MM as the gcode is parsed. Currently UGS doesn't have a good way of knowing what units GRBL is reporting, fortunately @philreindl is working on some improvements in this area that should help in a lot of areas - including the visualizer.

Here's one of the old tickets about this issue #96, which I thought was a duplicate of this but is actually describing a case that was fixed a long time ago (ironically, without the fix to that issue, the visualizer would have worked the way you expected).

**Comment by barnold96** [comment] 2016-01-23 02:18
Thank you for the update, Will.

--------------------------------------------
On Fri, 1/22/16, Will Winder <notifications@github.com> wrote:

 Subject: Re: [Universal-G-Code-Sender] Visualization Issue (#333)
 To: "winder/Universal-G-Code-Sender" <Universal-G-Code-Sender@noreply.github.com>
 Cc: "barnold96" <bb31757@yahoo.com>
 Date: Friday, January 22, 2016, 10:40 AM
 
 This is a known limitation to how
 the visualizer was implemented, basically the drawing code
 converts everything to MM as the gcode is parsed. Currently
 UGS doesn't have a good way of knowing what units GRBL
 is reporting, fortunately @philreindl is working
 on some improvements in this area that should help in a lot
 of areas - including the visualizer.
 
 Here's one of the old tickets about this issue #96, which I thought was a
 duplicate of this but is actually describing a case that was
 fixed a long time ago (ironically, without the fix to that
 issue, the visualizer would have worked the way you
 expected).
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by philreindl** [comment] 2016-01-23 14:39
The central theme of the work I was doing (which should be ready to merge, btw) is to isolate the jog gcode commands from the "real" gcode that's being run.  In order to do this we need to track units and motion mode.  As it sits, those things aren't exposed for the visualizer to use.  But I would expect it would be pretty straightforward to do so.

**Closed** 2016-02-18 14:12 UTC
Labels: bug
