### ISSUE TITLE
(Suggestion) Seperate jog sizes for the XY and Z axis

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#392] opened 2016-04-16 04:44 UTC
Lets be honest, we're not jogging our Z by 50mm so how about 2 controls, one for each? That way I can arrow key in 50mm increments for XY, and pgdown/pgup 5mm for my Z. Maybe even a multiplier option? (Like as I just gave as an example, Z moves 1/10th as the other 2 axis)

There are also a few other issues right now Will, like the common macro window still being disabled even if you connect to your arduino in the latest build. Please fix!

Cheers,

**Comment by philreindl** [comment] 2016-04-17 01:02
For the macro window issue, can you please provide more details?  Are you using the classic or platform gui?

**Comment by jahnj0584** [comment] 2016-04-25 13:30
I forget actually. Ill download the latest version and see if its still there.

**Comment by jahnj0584** [comment] 2016-04-27 19:07
macro still doesnt work. Opened another thread for it.

**Comment by jahnj0584** [comment] 2016-05-09 13:01
still want to see this implemented

**Comment by winder** [comment] 2016-05-14 22:01
Just noticed this is a duplicate of #217

**Closed by winder** 2016-05-14 22:01 UTC
Labels: duplicate, suggestion
