### ISSUE TITLE
Cannot perform soft reset after activating hard limit in UGS 2.0

### ISSUE THREAD

**Issue by rehakmatej** [winder/Universal-G-Code-Sender#684] opened 2017-07-06 08:23 UTC
UGS 2.0 is great. Thank you for it. But in UGS 2.0 I can't perform soft reset after activating hard limit. Soft reset and other buttons stay disabled. In UGS 1.0.9 I can normally perform soft reset and $X after activating hard limit.

**Comment by vMeph** [comment] 2017-07-06 08:34
if Hard limits is trigger you need to reset arduino, for safety questions

**Comment by aforww** [comment] 2017-07-08 16:57
I've been having that issue but with soft limits. As I understood it the 0x8 (ctrlX) should soft reset these alarms right? Or am I completely wrong in this?

**Comment by winder** [comment] 2017-07-09 15:02
Duplicate of #563

**Closed by winder** 2017-07-09 15:02 UTC
Labels: bug, duplicate
