### ISSUE TITLE
UGS does not respond via USB connection

### ISSUE THREAD

**Issue by cgerrist** [winder/Universal-G-Code-Sender#2220] opened 2023-05-13 16:16 UTC
### Version

2.0.17

### Hardware / Firmware

GRBL 1.1

### What happened

After installing the latest version, UGS do not respond when I make a connection to a Arduino Mega with lastes Grbl software.
I need to do a hardware reset then it makes connection. First I thought it has something to do with de Grbl software. I tested also with 'Better GRBL' via octoprint. This software has no issues.
What I see is the the RX light flashes every second.
After a hardware reset it works but sometimes the Arduino gives an boot error.
When it works the rx and tx light flickers every half a second.

### How to reproduce

Connect to a Arduino Mage with the latest Grbl and make a connection.
When It hang give an hardware reset. Them it continue. 

### Operating System

I have a Mac mini M2 with the latstes

**Comment by breiler** [comment] 2023-05-14 13:22
Closing as this is a duplicate of #2221

**Closed by breiler** 2023-05-14 13:22 UTC
Labels: duplicate
