### ISSUE TITLE
Real Time keyboard joggin akin to SourceRabbit

### ISSUE THREAD

**Issue by jahnj0584** [winder/Universal-G-Code-Sender#891] opened 2018-02-10 01:58 UTC

**Comment by breiler** [comment] 2018-02-11 08:03
How do you mean? 
What I can see, both UGS and SourceRabbit uses the GRBL $J-command for jogging.

**Comment by jahnj0584** [comment] 2018-02-11 18:31
If you use keyboard commands to jog, the machine still continues after you
depress the key.

**Comment by winder** [comment] 2018-02-13 13:32
Duplicate of #779

**Closed by winder** 2018-02-13 13:32 UTC
