### ISSUE TITLE
Visualiser and Joystick setting not being brought into new versions

### ISSUE THREAD

**Issue by marshr32** [winder/Universal-G-Code-Sender#2119] opened 2023-01-12 20:50 UTC
### Version

2.0.13

### Hardware / Firmware

GRBL 1.1

### What happened

Both 2.0.13 and the latest nightly are not bringing across my visualiser and joystick settings from 2.0.12.
Window positions seem to be read OK (but only on the second startup with 2.0.13)

### Operating System

Win 10

**Comment by breiler** [comment] 2023-01-12 21:02
In version 2.0.12 and earlier we had a setting that should have placed configurations files according to this:
https://github.com/winder/Universal-G-Code-Sender/wiki/Configuration#configuration-files

Unfortunately this setting was wrong which sometimes led to configuration files being placed in random places. The issue is fixed as of 2.0.13 and the configuration files should be retained between upgrades. There is no way for us to automatically migrate them to the new location so they are unfortunately lost...

Closing as "won't fix".

**Closed by breiler** 2023-01-12 21:02 UTC

**Comment by marshr32** [comment] 2023-01-12 23:51
No worries, it's not a huge job to set them again, just thought I'd mention it.
Thanks for all your awesome work on UGS 😁

Jan 13, 2023 10:02:40 AM Joacim Breiler ***@***.***>:

**Comment by marshr32** [comment] 2023-01-13 00:38
For anyone who sees this later, you can export settings from the old version and import them in the new one. This gets most things sorted.
