### ISSUE TITLE
UGS send gcode end stop here

### ISSUE THREAD

**Issue by viewsat** [winder/Universal-G-Code-Sender#348] opened 2016-02-18 09:26 UTC
Raspberry pi 2 B use UGS,send gcode end stop here.
See video >>  https://youtu.be/Xer7LnWyTIc

**Comment by viewsat** [comment] 2016-02-18 09:28
My Raspberry pi 2 B use official supported operating system. 
RASPBIAN JESSIE
Full desktop image based on Debian Jessie
Version:February 2016
Release date:2016-02-09
Kernel version:4.1

**Comment by winder** [comment] 2016-02-18 14:28
Duplicate of #340 I haven't been able to reproduce this one yet.

**Closed by winder** 2016-02-18 14:28 UTC
Labels: bug, duplicate
