### ISSUE TITLE
Not Detecting Serial Port

### ISSUE THREAD

**Issue by WaltRh** [winder/Universal-G-Code-Sender#1190] opened 2019-02-10 20:56 UTC
## Feature request

U
## Problem description 
using a Dell laptop, with Platform UGS, while connecting to the Bobs CNC E3 there are no options for the serial port even when refreshed. Using a USB connection. Tried all 3 on laptop.

### Steps to Reproduce the Problem

  1.
  1.
  1.

**Comment by WaltRh** [comment] 2019-02-10 20:57
Please any help would be appreciated, looking forward to working with this machine, but stuck at the moment.

**Comment by JacksCrafts** [comment] 2019-02-10 21:08
Did you hit the refresh button next to where it says port?
Look in your device manager to confirm your Comport. .. COM 3 or COM 4

**Comment by WaltRh** [comment] 2019-02-10 21:15
Yes, I hit the refresh each time, but nothing shows up...strange

**Comment by JacksCrafts** [comment] 2019-02-10 21:21
What are you on Windows 10, using Arduino with CNC shield?
If you right click the start button you should see a short cut to Device Manager.
In there you can see if you com port is connected.

**Comment by WaltRh** [comment] 2019-02-10 21:23
I am using Windows 7 and Platform UGS

**Comment by JacksCrafts** [comment] 2019-02-10 21:25
You can probably type in Device Manager down in the lower left corner.
And is your buad set at 115200?

**Comment by JacksCrafts** [comment] 2019-02-10 21:31
If you go to your control panel.
Then hit hardware you will see Device manager.

**Comment by JacksCrafts** [comment] 2019-02-10 21:32
![device mngr](https://user-images.githubusercontent.com/44066988/52539903-7c265a80-2d51-11e9-8c74-833d22c47052.jpg)

**Comment by JacksCrafts** [comment] 2019-02-10 21:46
If you don't have Ports (COM) in your device manager you may need to flash GRBL onto you arduino.

**Comment by WaltRh** [comment] 2019-02-10 23:50
JackCrafts,
Thank you for your help. I didn't have Arduino installed, I then installed
it and found the port it was in and typed it in, which allowed me to
connect and home the machine. So far so good, now I just have to learn to
use it, so I may have more questions coming.
Thanks again!!

**Comment by JacksCrafts** [comment] 2019-02-11 00:07
You are welcome,
Glad I could help.

**Comment by breiler** [comment] 2019-02-19 18:41
Are you satisfied with the work around?

Otherwise you could try to change the connection driver. This should allow the program to automatically detect the port.

See instructions here: https://github.com/winder/Universal-G-Code-Sender/issues/940#issuecomment-392761818

**Comment by misan** [comment] 2019-02-21 18:32
Same problem here with Mojave OSX. Arduino sees the ports, CoolTerm sees the ports but not UGS nor ugsplatform nightly builds see any serial port in my computer.

**Comment by breiler** [comment] 2019-02-21 18:35
> Same problem here with Mojave OSX. Arduino sees the ports, CoolTerm sees the ports but not UGS nor ugsplatform nightly builds see any serial port in my computer.

Have your tried switching to the  jSerialComm driver (#940)?

**Comment by misan** [comment] 2019-02-21 18:35
ugsplatform using JSerialComm works as suggested in #940

**Comment by breiler** [comment] 2019-03-02 06:05
Closing this as it's a duplicate of #940

**Closed by breiler** 2019-03-02 06:05 UTC
